sudo: required

language: cpp
compiler:
- gcc
- clang

before_install:
- git checkout $TRAVIS_BRANCH

- if [ $(bii-support/travis/git/is_last_commit_travis.sh) = "true" ] ; then exit 0 ; fi
- bii-support/travis/git/configure.sh

install:
- bii-support/travis/install/all-headless.sh

- export TRAVIS_CXX=$CXX

script:
- bii-support/linux/build/default.sh
- valgrind --leak-check=full "bin/${USER}_${BLOCK_NAME}_test_main"

after_success:
- bii-support/travis/publish/biicode.sh

env:
  global:
  - USER_EMAIL=azriel91@gmail.com
  - USER_NAME="azriel"
  - BLOCK_NAME=usbundleloader
  - USER=azriel
  # BII_PASSWORD
  - secure: "Ti6S0ZrXRZAbavhwoaK8JXJ5BzZ5GEckFaaDjFxhOcg+LvxMaAO9w/l38jOUimQ94U+kg73ccuh2ZZgSu8MMNjEDefVb855BCl+kzmTW7QQ61mMCq5WE51kiTFug56WVXgvh1oarSRkdeOM9dS0I3MOJIFQt2dQvIcwGpAqBOto="
  # GITHUB_TOKEN
  - secure: "aO4zaAI81jlakJFynpO6/2nJ2WlMmMPypIQDV7o13zV78TSXsV+3+qSjhU+TXfjQXDxl8evT4ggTkZTHPyu9AExZusciA3xOD/0tdtYr0F9N9rB/sPaQLpPsHY/aWBtApqASKuR/4gHc404CCX4SGn68Kpp8d9CzdlHpLZi6xN4="
  matrix:
  - BUILD_SHARED_LIBS=OFF
  - BUILD_SHARED_LIBS=ON