install:
- cmd: git submodule update --init --recursive
- cmd: bii-support\appveyor\install\all-headless.bat

build_script:
- cmd: bii-support\windows\build\default.bat

test_script:
- cmd: bin\%BII_USER%_%BLOCK_NAME%_test_main.exe

environment:
  BLOCK_NAME: usbundleloader
  BII_USER: azriel

  matrix:
  - BUILD_SHARED_LIBS: OFF
  - BUILD_SHARED_LIBS: ON